spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: admin
    password: secret
# External logging configuration
external:
  logging:
    url: https://tools-httpstatus.pickup-services.com/200